---
- name: yum
  yum: name={{item}} state=latest
  with_items: "{{ python_yum }}"

- name: unarchive
  unarchive:
    src: "{{ python_url }}"
    dest: "{{ python_tmp }}"
    remote_src: True
  register: reg

- name: make
  shell: cd "{{ python_dir }}" && ./configure --prefix=/usr/local/python && make && make install

- file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - { src: '/usr/local/python/bin/python3', dest: '/usr/local/bin/python' }
    - { src: '/usr/local/python/bin/pip3' , dest: '/usr/local/bin/pip' }
